baseURL: # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: Anthony Marino
paginate: 5
theme: charlolamode



menu:
    main:
        #- name: Contact
        #  url: /contact/
        #  weight: 30
        #- name: Articles
        # url: /articles/
        # weight: 20
        - name: Resume
          url: /docs/resume.pdf
          weight: 15

     # - name: Categories
        #   url: /categories/
        #   weight: 10
        # - name: new Tab
        #   url: /newtab/
        #   weight: defines order of tabs
   


params:
    author: Anthony Marino


    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    displayFullLangName: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true

    profileMode:
        # Disable to populate home page with 'mainSections' content
        enabled: true
        title: Anthony Marino
        description:
        imageUrl: "/images/profile.png.jpg"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Don't click me
              url: "https://www.youtube.com/@Anton-does-cyber"
    mainSections:
      - articles

    socialIcons:
        - name: buymeacoffee
          url: "https://buymeacoffee.com/anton.cyber"
        - name: github
          url: "https://github.com/Anthonywolf17"
        - name: linkedin
          url: "https://www.linkedin.com/in/anthony-marino7/"

      
        - name: youtube
          url: "https://www.youtube.com/@Anton-does-cyber"
      # - name: twitter
      #   url: yoururl
      # - name: facebook
      #   url: yoururl


    # change favicon in images folder (icon for web tab)
    assets:
          favicon: "/images/favicon.ico"
          favicon16x16: "/images/favicon-16x16.png"
          favicon32x32: "/images/favicon-32x32.png"
          apple_touch_icon: "/images/apple-touch-icon.png"
          safari_pinned_tab: "/images/apple-touch-icon.png"



enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true

